name: Auto Comment
on:
  pull_request_target:
    types: [ labeled ]
jobs:
  if: ${{ github.event.label.name == ':sparkles: Merged:' }}
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestLabeled: >
            Thanks @{{ author }} !!
            Make sure to give the repository a star and share about it as well!
            You can tweet about the repository as well using the tweet badge on the Readme file or Website!
